# Haversine Formula

[Credit](https://www.geeksforgeeks.org/dsa/haversine-formula-to-find-distance-between-two-points-on-a-sphere/)

In [1]:
import pandas as pd
import math

In [2]:
df = pd.read_csv('../data/2025-citibike-clean.csv', index_col=[0])
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,month,day_name,trip_duration
0,56BD148A05E26915,Electric Bike,2025-01-01 22:19:06.324,2025-01-01 22:23:32.899,W 36 St & 7 Ave,6483.06,W 24 St & 7 Ave,6257.03,40.752149,-73.989539,40.744876,-73.995299,Member,1,Wednesday,266.575
1,700CCCDF00C08077,Electric Bike,2025-01-09 15:20:43.991,2025-01-09 15:26:19.137,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,Member,1,Thursday,335.146
2,B1A3FAFA5FE651CE,Electric Bike,2025-01-01 12:54:26.571,2025-01-01 13:03:03.565,Jackson Ave & 46 Rd,6203.02,Crescent St & Broadway,6827.11,40.745248,-73.947333,40.763359,-73.928647,Member,1,Wednesday,516.994
3,9CB0F28054BA5EBC,Electric Bike,2025-01-14 13:43:59.151,2025-01-14 13:49:04.543,Broadway & E 19 St,5980.11,W 24 St & 7 Ave,6257.03,40.738290,-73.990060,40.744876,-73.995299,Member,1,Tuesday,305.392
4,A1B8FDD4FAF0C2B2,Electric Bike,2025-01-13 07:20:37.176,2025-01-13 07:29:18.015,Willis Ave & E 143 St,7798.02,1 Ave & E 110 St,7522.02,40.812299,-73.920370,40.792327,-73.938300,Member,1,Monday,520.839

In [3]:
def haversine(lat1, lon1, lat2, lon2):
    dLat = (lat2 - lat1) * math.pi / 180.0
    dLon = (lon2 - lon1) * math.pi / 180.0

    lat1 = (lat1) * math.pi / 180.0
    lat2 = (lat2) * math.pi / 180.0

    a = (pow(math.sin(dLat / 2), 2) + 
         pow(math.sin(dLon / 2), 2) * 
             math.cos(lat1) * math.cos(lat2));
    rad = 6371
    c = 2 * math.asin(math.sqrt(a))
    return rad * c * 0.6213711922

In [4]:
df['miles'] = df.apply(lambda col: haversine(col['start_lat'], col['start_lng'], col['end_lat'], col['end_lng']), axis=1)

In [5]:
df.to_parquet('../data/2025-citibike.parquet')